# Generated by Django 2.0.7 on 2019-09-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0002_auto_20190907_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departamento_text',
            field=models.CharField(choices=[('CRC', 'CRC'), ('Registro Civil', 'Registro Civil'), ('CRC Jud', 'CRC Jud')], max_length=200),
        ),
    ]
